function Qg = grav(L,g)
%GRAV
%    QG = GRAV(L,G)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    18-Dec-2013 08:27:21

t2 = g(1);
t3 = g(2);
t4 = g(3);
t5 = t2.*(1.0./2.0);
t6 = t3.*(1.0./2.0);
t7 = t4.*(1.0./2.0);
t8 = L.*t2.*(1.0./1.2e1);
t9 = L.*t3.*(1.0./1.2e1);
t10 = L.*t4.*(1.0./1.2e1);
Qg = [t5;t6;t7;t8;t9;t10;t5;t6;t7;-t8;-t9;-t10];
