function kappa_kappa_e = kappa_kappa_e(Sx,Sxx,coef,inv_rx_rx_cubed,rx,rxx,v)
%KAPPA_KAPPA_E
%    KAPPA_KAPPA_E = KAPPA_KAPPA_E(SX,SXX,COEF,INV_RX_RX_CUBED,RX,RXX,V)

%    This function was generated by the Symbolic Math Toolbox version 5.10.
%    17-Dec-2013 14:53:01

t2 = Sx(1);
t3 = Sxx(1);
t4 = rx(1);
t5 = v(3);
t6 = rxx(3);
t7 = t2.*t6;
t8 = rx(3);
t9 = t7-t3.*t8;
t10 = rx(2);
t11 = rxx(1);
t12 = t3.*t4;
t13 = v(2);
t14 = rxx(2);
t15 = t3.*t10;
t16 = v(1);
t17 = t15-t2.*t14;
t18 = t12-t2.*t11;
t19 = Sx(2);
t20 = Sxx(2);
t21 = t6.*t19;
t22 = t21-t8.*t20;
t23 = t4.*t20;
t24 = t10.*t20;
t25 = t24-t14.*t19;
t26 = t23-t11.*t19;
t27 = Sx(3);
t28 = Sxx(3);
t29 = t6.*t27;
t30 = t29-t8.*t28;
t31 = t4.*t28;
t32 = t10.*t28;
t33 = t32-t14.*t27;
t34 = t31-t11.*t27;
t35 = Sx(4);
t36 = Sxx(4);
t37 = t6.*t35;
t38 = t37-t8.*t36;
t39 = t4.*t36;
t40 = t10.*t36;
t41 = t40-t14.*t35;
t42 = t39-t11.*t35;
kappa_kappa_e = [-inv_rx_rx_cubed.*(t5.*t17+t9.*t13+coef.*t2.*t4),inv_rx_rx_cubed.*(t5.*t18+t9.*t16-coef.*t2.*t10),-inv_rx_rx_cubed.*(t13.*t18-t16.*t17+coef.*t2.*t8),-inv_rx_rx_cubed.*(t5.*t25+t13.*t22+coef.*t4.*t19),inv_rx_rx_cubed.*(t5.*t26+t16.*t22-coef.*t10.*t19),-inv_rx_rx_cubed.*(t13.*t26-t16.*t25+coef.*t8.*t19),-inv_rx_rx_cubed.*(t5.*t33+t13.*t30+coef.*t4.*t27),inv_rx_rx_cubed.*(t5.*t34+t16.*t30-coef.*t10.*t27),-inv_rx_rx_cubed.*(t13.*t34-t16.*t33+coef.*t8.*t27),-inv_rx_rx_cubed.*(t5.*t41+t13.*t38+coef.*t4.*t35),inv_rx_rx_cubed.*(t5.*t42+t16.*t38-coef.*t10.*t35),-inv_rx_rx_cubed.*(t13.*t42-t16.*t41+coef.*t8.*t35)];
